### PR TITLE
New Feature: Change the size of Eraser & Paint

### PR DESCRIPTION
**Pull request by Ayushivvv**
Now, the user has the option to change the size of the eraser and the paint, with the minimum size being 1 and the maximum being 30. As the user uses the spinner, the numbers increase and decrease to their desired value, and the size also changes accordingly.

### CODE REVIEW

**Review by rosej12 — COMMENTED** [review]
Code and style is good for the new feature. Parts of ColorAPI.java have been deleted though. Was this an accident?

**Comment by Ayushivvv** [comment]
Hey Rosanna, this was purely an accident, and I think I did not have parts of the code in my file. All my files in the main and ayushi_v branches were up-to-date. Thus, the changes compared to the main files look like they were deleted.

**Comment by rosej12** [comment]
Ok, this feature doesn't need changes in that file, so that makes sense. Just add another commit where you add the code back and it should be fine.

**Review by rosej12 — APPROVED** [review]
Everything looks good now.

**Review by peachvegetable — APPROVED** [review]

**Review by robertjhaughton — APPROVED** [review]
Everything seems ok. Your code looks correct and clean.

**Pull request merged**
