### PR TITLE
Generate Random Color Use Case

### PR DESCRIPTION
**Pull request by robertjhaughton**
Fixed my implementation so that it now follows our current structure of clean architecture and SOLID design principles.

### CODE REVIEW

**Comment by rosej12** [comment]
What is the "target" folder for? You have two copies of a lot of files, one in the src/main/java we are using and one in the target folder.

**Comment by robertjhaughton** [comment]
> What is the "target" folder for? You have two copies of a lot of files, one in the src/main/java we are using and one in the target folder.

Sorry, that was a mistake to add. The target folder is what gets auto-generated, I did not mean to commit that folder. I'll try to remove it. Maybe we should add it to our gitignore file.

**Review by peachvegetable — APPROVED** [review]
good change since the code structure is now follwing CA and SOLIC

**Comment by robertjhaughton** [comment]
> The code and structure looks good. Issues I noticed though:
> 
> * The colors shown are incorrect even though once selected, we can draw with the right color
> * I had issues running your test file. I keep getting a "java: package org.junit does not exist" error. Do you have any idea why? I tried reloading Maven and stuff but it still doesn't work.

1. I am still trying to find out what could be causing the palette not visually to update. Let me know if you see what could be the issue.

2.  It works for me. Did you try hovering the line? It should give you the option to add the JUnit dependency. Attached is the test along with the code coverage. 
Screenshot 2024-12-01 193438

**Comment by rosej12** [comment]
> 2. It works for me. Did you try hovering the line? It should give you the option to add the JUnit dependency. Attached is the test along with the code coverage.

If I hover over the import statement, I get the option "add 'JUnit4‘ to classpath", but even after I click that I still get the error...

**Comment by rosej12** [comment]
> > 2. It works for me. Did you try hovering the line? It should give you the option to add the JUnit dependency. Attached is the test along with the code coverage.
> 
> If I hover over the import statement, I get the option "add 'JUnit4‘ to classpath", but even after I click that I still get the error...

Nevermind. I got it to work by unlinking and relinking as Maven project.

**Review by rosej12 — APPROVED** [review]

**Review by Ayushivvv — APPROVED** [review]
I like how it follows clean architecture.

**Pull request merged**
