### PR TITLE
Implemented Sketch to Render Use Case

### PR DESCRIPTION
**Pull request by rosej12**
Implemented:
- switching between Drawing View and Render View
- Letting the user enter a description and get a render of their sketch

### CODE REVIEW

**Review by Ayushivvv — APPROVED** [review]
Looks good! Remember to create tests to test your code.

**Review by robertjhaughton — APPROVED** [review]
Your code seems correct and clean. You adhered to clean architecture. Additionally, you included Javadocs and relevant comments. Everything looks good!

**Review by peachvegetable — COMMENTED** [review]
good implementation of RenderView, and it provides the user to switch btw drawingview and renderview which is what we needed.

**Review by peachvegetable — APPROVED** [review]
merge approved

**Comment by rosej12** [comment]
renderTestCoverage
I've added the tests.

**Pull request merged**
